
trigger:
 - main

# strategy:
#   maxParallel: 1

# pool:
#    vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        
        echo "Hello World"
