server:
  port: 8080

spring:
  application:
    name: springbootdemo
  config:
    import:
      - optional:vault://
      - optional:file:/etc/config/application-override.properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  #cloud:
  #  vault:
  #    host: localhost
  #    port: 8200
  #    scheme: http
  #    uri: http://localhost:8200
  #    connection-timeout: 5000
  #    read-timeout: 15000
  #    token: s.To7q12r59B6XSLXj3tV3BPaq
  datasource:
    username: postgres
    password: postgres
    initialization-mode :  always
    url: jdbc:postgresql://postgres:5432/postgresdb
    driverClassName: org.postgresql.Driver

logging:
  level:
    com:
      psl: INFO