server:
  port: 9090

spring:
  application:
    name: springbootdemo
  config:
    import:
      - optional:vault://
      - optional:/etc/config/property-override.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      uri: http://localhost:8200
      connection-timeout: 5000
      read-timeout: 15000
      token: s.To7q12r59B6XSLXj3tV3BPaq
  datasource:
    username: ${dbusername}
    password: ${dbpassword}
    initialization-mode :  always
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver