apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: "sbdemo:v4"
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30      
      volumes:
        - name: config-volume
          configMap:
            name: appconfig